# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"4\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"G\n\x11\x45mbeddingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nembeddings\x18\x02 \x03(\x02\x12\r\n\x05\x65rror\x18\x03 \x01(\t2[\n\x10\x45mbeddingService\x12G\n\x0cGetEmbedding\x12\x17.embedding.ImageRequest\x1a\x1c.embedding.EmbeddingResponse\"\x00\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_IMAGEREQUEST']._serialized_start=30
  _globals['_IMAGEREQUEST']._serialized_end=82
  _globals['_EMBEDDINGRESPONSE']._serialized_start=84
  _globals['_EMBEDDINGRESPONSE']._serialized_end=155
  _globals['_EMBEDDINGSERVICE']._serialized_start=157
  _globals['_EMBEDDINGSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
